# image will be published to ghcr.io/<user>/<name>
name: sway
# description will be included in the image's metadata
description: This is my personal sway OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/wayblueorg/sway
image-version: 40 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: rpm-ostree
    repos: 
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
    install:
      - stow
      - gum
      - starship
      - hplib
      - solaar
      # - gcc # for brew in the future
    remove:
      - firefox
      - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

  - from-file: docker.yml
  - from-file: virtualization.yml

  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode # don't add spaces or "Nerd Font" suffix
        - Hack
        - Meslo
        - RobotoMono
        - SourceCodePro
        - Terminus
        - JetBrainsMono
        - NerdFontsSymbolsOnly
  
  - type: justfiles
    include: 
      - myjust.just

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      # repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      # repo-name: flathub
      # repo-title: "Flathub (system-wide)" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
      install:
         - com.slack.Slack
         - io.dbeaver.DBeaverCommunity
         - com.nextcloud.desktopclient.nextcloud
         - org.chromium.Chromium
         - org.telegram.desktop
         - com.spotify.Client
         - com.microsoft.Edge
         - com.discordapp.Discord
         - com.github.tchx84.Flatseal
         - it.mijorus.gearlever
         - org.mozilla.firefox
         - com.vscodium.codium
         - org.flameshot.Flameshot
         - io.missioncenter.MissionCenter
      remove:

  - from-file: gaming.yml

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

